import { BackgroundVariant } from '@xyflow/react'

export interface GraphTheme {
  id: string
  name: string
  /** Representative swatch color shown in the picker */
  swatch: string
  bgVariant: BackgroundVariant
  bgPatternColor: string
  canvasBg: string
  /** CSS custom properties applied to the canvas container */
  vars: Record<string, string>
}

export const THEMES: GraphTheme[] = [
  {
    id: 'default',
    name: 'Default',
    swatch: '#94a3b8',
    bgVariant: BackgroundVariant.Dots,
    bgPatternColor: '#cbd5e1',
    canvasBg: '#f8fafc',
    vars: {
      '--gt-node-bg': '#ffffff',
      '--gt-node-border': '#e2e8f0',
      '--gt-node-name': '#0f172a',
      '--gt-node-sub': '#475569',
      '--gt-node-muted': '#64748b',
      '--gt-node-avatar-bg': '#e2e8f0',
      '--gt-node-avatar-text': '#475569',
      '--gt-node-handle': '#94a3b8',
      '--gt-node-handle-border': '#ffffff',
      '--gt-node-ring': '#0ea5e9',
      '--gt-node-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      '--gt-edge': '#64748b',
      '--gt-edge-selected': '#0ea5e9',
      '--gt-edge-label-bg': 'rgba(255,255,255,0.9)',
      '--gt-edge-label-text': '#334155',
      '--gt-edge-label-border': '#e2e8f0',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    swatch: '#1e293b',
    bgVariant: BackgroundVariant.Dots,
    bgPatternColor: '#334155',
    canvasBg: '#0f172a',
    vars: {
      '--gt-node-bg': '#1e293b',
      '--gt-node-border': '#334155',
      '--gt-node-name': '#f1f5f9',
      '--gt-node-sub': '#cbd5e1',
      '--gt-node-muted': '#94a3b8',
      '--gt-node-avatar-bg': '#334155',
      '--gt-node-avatar-text': '#e2e8f0',
      '--gt-node-handle': '#64748b',
      '--gt-node-handle-border': '#1e293b',
      '--gt-node-ring': '#60a5fa',
      '--gt-node-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.5)',
      '--gt-edge': '#94a3b8',
      '--gt-edge-selected': '#60a5fa',
      '--gt-edge-label-bg': 'rgba(30,41,59,0.95)',
      '--gt-edge-label-text': '#e2e8f0',
      '--gt-edge-label-border': '#334155',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    swatch: '#4ade80',
    bgVariant: BackgroundVariant.Dots,
    bgPatternColor: '#bbf7d0',
    canvasBg: '#f0fdf4',
    vars: {
      '--gt-node-bg': '#ffffff',
      '--gt-node-border': '#86efac',
      '--gt-node-name': '#14532d',
      '--gt-node-sub': '#166534',
      '--gt-node-muted': '#15803d',
      '--gt-node-avatar-bg': '#dcfce7',
      '--gt-node-avatar-text': '#166534',
      '--gt-node-handle': '#4ade80',
      '--gt-node-handle-border': '#ffffff',
      '--gt-node-ring': '#16a34a',
      '--gt-node-shadow': '0 4px 6px -1px rgb(20 83 45 / 0.2)',
      '--gt-edge': '#4ade80',
      '--gt-edge-selected': '#16a34a',
      '--gt-edge-label-bg': 'rgba(255,255,255,0.9)',
      '--gt-edge-label-text': '#14532d',
      '--gt-edge-label-border': '#86efac',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    swatch: '#38bdf8',
    bgVariant: BackgroundVariant.Lines,
    bgPatternColor: '#bae6fd',
    canvasBg: '#f0f9ff',
    vars: {
      '--gt-node-bg': '#ffffff',
      '--gt-node-border': '#7dd3fc',
      '--gt-node-name': '#0c4a6e',
      '--gt-node-sub': '#0369a1',
      '--gt-node-muted': '#0284c7',
      '--gt-node-avatar-bg': '#e0f2fe',
      '--gt-node-avatar-text': '#0369a1',
      '--gt-node-handle': '#38bdf8',
      '--gt-node-handle-border': '#ffffff',
      '--gt-node-ring': '#0284c7',
      '--gt-node-shadow': '0 4px 6px -1px rgb(12 74 110 / 0.2)',
      '--gt-edge': '#38bdf8',
      '--gt-edge-selected': '#0284c7',
      '--gt-edge-label-bg': 'rgba(255,255,255,0.9)',
      '--gt-edge-label-text': '#0c4a6e',
      '--gt-edge-label-border': '#7dd3fc',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    swatch: '#fb923c',
    bgVariant: BackgroundVariant.Dots,
    bgPatternColor: '#fed7aa',
    canvasBg: '#fff7ed',
    vars: {
      '--gt-node-bg': '#ffffff',
      '--gt-node-border': '#fdba74',
      '--gt-node-name': '#7c2d12',
      '--gt-node-sub': '#9a3412',
      '--gt-node-muted': '#c2410c',
      '--gt-node-avatar-bg': '#ffedd5',
      '--gt-node-avatar-text': '#9a3412',
      '--gt-node-handle': '#fb923c',
      '--gt-node-handle-border': '#ffffff',
      '--gt-node-ring': '#ea580c',
      '--gt-node-shadow': '0 4px 6px -1px rgb(124 45 18 / 0.2)',
      '--gt-edge': '#fb923c',
      '--gt-edge-selected': '#ea580c',
      '--gt-edge-label-bg': 'rgba(255,255,255,0.9)',
      '--gt-edge-label-text': '#7c2d12',
      '--gt-edge-label-border': '#fdba74',
    },
  },
  {
    id: 'vintage',
    name: 'Vintage',
    swatch: '#fbbf24',
    bgVariant: BackgroundVariant.Cross,
    bgPatternColor: '#d6c9a8',
    canvasBg: '#fef9ef',
    vars: {
      '--gt-node-bg': '#fffbf0',
      '--gt-node-border': '#d6c9a8',
      '--gt-node-name': '#451a03',
      '--gt-node-sub': '#78350f',
      '--gt-node-muted': '#92400e',
      '--gt-node-avatar-bg': '#fde68a',
      '--gt-node-avatar-text': '#78350f',
      '--gt-node-handle': '#b45309',
      '--gt-node-handle-border': '#fffbf0',
      '--gt-node-ring': '#b45309',
      '--gt-node-shadow': '0 4px 6px -1px rgb(69 26 3 / 0.2)',
      '--gt-edge': '#b45309',
      '--gt-edge-selected': '#78350f',
      '--gt-edge-label-bg': 'rgba(255,251,240,0.95)',
      '--gt-edge-label-text': '#451a03',
      '--gt-edge-label-border': '#d6c9a8',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    swatch: '#c7d2fe',
    bgVariant: BackgroundVariant.Lines,
    bgPatternColor: '#f1f5f9',
    canvasBg: '#ffffff',
    vars: {
      '--gt-node-bg': '#ffffff',
      '--gt-node-border': '#f1f5f9',
      '--gt-node-name': '#0f172a',
      '--gt-node-sub': '#64748b',
      '--gt-node-muted': '#94a3b8',
      '--gt-node-avatar-bg': '#f8fafc',
      '--gt-node-avatar-text': '#64748b',
      '--gt-node-handle': '#cbd5e1',
      '--gt-node-handle-border': '#ffffff',
      '--gt-node-ring': '#6366f1',
      '--gt-node-shadow': '0 1px 3px rgb(0 0 0 / 0.06)',
      '--gt-edge': '#cbd5e1',
      '--gt-edge-selected': '#6366f1',
      '--gt-edge-label-bg': 'rgba(255,255,255,0.9)',
      '--gt-edge-label-text': '#334155',
      '--gt-edge-label-border': '#f1f5f9',
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    swatch: '#22d3ee',
    bgVariant: BackgroundVariant.Dots,
    bgPatternColor: '#1e293b',
    canvasBg: '#030712',
    vars: {
      '--gt-node-bg': '#0f172a',
      '--gt-node-border': '#22d3ee',
      '--gt-node-name': '#f0f9ff',
      '--gt-node-sub': '#a5f3fc',
      '--gt-node-muted': '#67e8f9',
      '--gt-node-avatar-bg': '#164e63',
      '--gt-node-avatar-text': '#22d3ee',
      '--gt-node-handle': '#22d3ee',
      '--gt-node-handle-border': '#0f172a',
      '--gt-node-ring': '#f0abfc',
      '--gt-node-shadow': '0 0 0 1px #22d3ee, 0 4px 12px -1px rgb(34 211 238 / 0.3)',
      '--gt-edge': '#22d3ee',
      '--gt-edge-selected': '#f0abfc',
      '--gt-edge-label-bg': 'rgba(15,23,42,0.95)',
      '--gt-edge-label-text': '#22d3ee',
      '--gt-edge-label-border': '#22d3ee',
    },
  },
]

export const DEFAULT_THEME_ID = 'default'
